version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  #mounting the local file to the docker container, changes made after container up, container will not take new changes
    networks:
      - my-network
networks:
  my-network:
